print("cisla = [ int(x) for x in input().split() ]")
print("sum = 0")
print("for i in cisla:")
print("\tif(i == 6):")
print("\t\tsum += 1")
print("\telif(i == 1):")
print("\t\tsum -= 1")
print("if(sum > 0):")
print("\tprint(\"Alicka\")")
print("elif(sum == 0):")
print("\tprint(\"Remiza\")")
print("else:")
print("\tprint(\"Barborka\")")